i1 = 2
i2 = 5
i3 = -3
d1 = 2.0
d2 = 5.0
d3 = -0.5
a = int(i1 + i2)
print(a)
b = float(i1 / i2)
print(b)
c = float(i1 // i2)
print(c)
d = float(i2 / i1)
print(d)
e = float(i2 // i1)
print(e)
f = int(i1 * i3)
print(f)
g = float(d1 + d2)
print(g)
h = float(d1 / d2)
print(h)
i = float(d2 / d1)
print(i)
j = float(d3 * d1)
print(j)
k = float(d1 + i2)
print(k)
L = float(i1 / d2)
print(L)
m = float(d2 / i1)
print(m)
n = float(i2 / d1)
print(n)
o = float(i1 / i2 * d1)
print(o)
p = float(d1 * i1 / i2)
print(p)
q = float(d1 / d2 * i1)
print(q)
r = float(i1 * d1 / d2)
print(r)
s = float(i2 / i1 * d1)
print(s)
t = float(d1 * i2 / i1)
print(t)
u = float(d2 / d1 * i1)
print(u)
v =float(i1 * d2 / d1)
print(v)
